# Generated by Django 5.2.4 on 2025-07-19 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcommand',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlcommand',
            name='manual_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlcommand',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlcommand',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
