# Generated by Django 5.2.4 on 2025-07-20 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_systemconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('emergency_status', models.BooleanField(default=False)),
                ('operational_mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('pump_status', models.BooleanField(default=False)),
                ('valve_status', models.BooleanField(default=False)),
                ('moisture_threshold', models.IntegerField(default=30)),
                ('last_contact', models.DateTimeField(auto_now=True)),
                ('status_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Device Statuses',
                'ordering': ['-last_contact'],
            },
        ),
    ]
