# Generated by Django 5.2.4 on 2025-08-03 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0005_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': 'Historical Threshold', 'verbose_name_plural': 'Historical Thresholds'},
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='moisture_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, choices=[('banana', 'Banana'), ('maize', 'Maize'), ('beans', 'Beans'), ('coffee', 'Coffee'), ('cassava', 'Cassava'), ('rice', 'Rice'), ('tomato', 'Tomato'), ('potato', 'Potato'), ('sugarcane', 'Sugarcane'), ('vegetables', 'Vegetables')], max_length=50, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'Clay'), ('loamy', 'Loamy'), ('sandy', 'Sandy')], max_length=50, null=True)),
                ('soil_moisture_threshold', models.IntegerField(default=50, help_text='Optimal soil moisture threshold for the selected crop/soil (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
