# Generated by Django 5.2.4 on 2025-08-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0006_alter_threshold_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='last_modified',
        ),
    ]
