# Generated by Django 5.2.4 on 2025-11-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0007_remove_schedule_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcommand',
            name='valve_status',
        ),
        migrations.RemoveField(
            model_name='devicestatus',
            name='valve_status',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='valve_status',
        ),
    ]
